"""empty message

Revision ID: 36c445b0784b
Revises: 
Create Date: 2023-11-07 22:44:07.746796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c445b0784b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BestScores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=80), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BestScores')
    # ### end Alembic commands ###
