"""added game_mode

Revision ID: 3e67b8eb119a
Revises: 0d2de29dd6d8
Create Date: 2023-11-12 23:15:01.449036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e67b8eb119a'
down_revision = '0d2de29dd6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('secret_code',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('secret_code',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###
