"""rename columns

Revision ID: 5a72737684e9
Revises: c5ad038afc58
Create Date: 2023-11-12 17:36:25.679152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a72737684e9'
down_revision = 'c5ad038afc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_code_length', sa.Integer(), nullable=True))
        batch_op.drop_column('number_length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_length', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('secret_code_length')

    # ### end Alembic commands ###
