"""gamestate table added

Revision ID: 5c7f0257c136
Revises: 36c445b0784b
Create Date: 2023-11-09 21:37:46.760758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7f0257c136'
down_revision = '36c445b0784b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_state')
    # ### end Alembic commands ###
