"""Added Game model and updated fields

Revision ID: c5ad038afc58
Revises: 6a8b3ba3c244
Create Date: 2023-11-11 00:58:57.239953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5ad038afc58'
down_revision = '6a8b3ba3c244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_code', sa.String(length=4), nullable=False),
    sa.Column('guesses', sa.PickleType(), nullable=True),
    sa.Column('feedback', sa.PickleType(), nullable=True),
    sa.Column('player_won', sa.Boolean(), nullable=True),
    sa.Column('number_length', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('game_over', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='game_state_pkey')
    )
    op.drop_table('game')
    # ### end Alembic commands ###
